Hide rawdatalog delete
dolittle/Studio pull request #116
Opened 2021-09-24 09:23 UTC by woksin

## Summary

Hides the delete button for the raw data log view card

#### How to test
- Start with a clean cluster (or without raw-data-log and purchase-order)
- Click Microservices
- Click Create new microservice
- Click Create within the Purchase order api card
- Select Infor graphic
- Enter name
- Click next
- Enter username
- Enter password
- Click Next
- Click Microservices
- See that there is no delete button on the raw-data-log-v1 webhook microservice 

### Added

- canDelete property to microservice view card

### Changed

- Uses HTML5 hidden to hide delete button from raw data log microservice view card

2021-09-24 09:49 UTC, joelhoisko requested changes
Found a bug:

I followed your steps, and after creating the POAPI I get greeted by the usual error screen. Then I click'd on "MICROSERVICES" from the left nav to get to the overview page and raw-data-log-v1 still had a Delete button:
![image](https://user-images.githubusercontent.com/10163775/134654961-e09013ae-d3a7-42ca-987f-0bf52b6d3c62.png)

If I refresh the page the button dissappears:
![image](https://user-images.githubusercontent.com/10163775/134655024-f58923e7-4080-48c8-89cc-41cd0862b9d0.png)

So somehow the `kind` is not set properly for the rawdatalog ms upon going to the overview view on the first go. Or something like that.

2021-09-24 10:20 UTC, woksin commented
Ohhh nice catch 😁

2021-09-27 13:41 UTC, woksin commented
The way I solved this led me into a bug in platform-api that I fixed here https://github.com/dolittle/platform-api/pull/35

2021-09-27 14:01 UTC, joelhoisko approved these changes
Tried with the bugfix from https://github.com/dolittle/platform-api/pull/35 and works fine 👍

2021-09-27 14:01 UTC, merged