start stop k3d scripts
dolittle/Studio pull request #193
Opened 2022-05-20 09:49 UTC by vstdolittle

## Summary

Make it easier for developers to work for short periods on studio. By having a start/stop script one can save the state in studio under development and get back to it at a later stage. reset-local-k3d would clear all volumes.

### Added

- start-local-k3d
- stop-local-k3d

### Changed

- Added documentation for the new scripts

2022-05-24 09:07 UTC, joelhoisko requested changes
Thanks for the PR, docs and helper scripts are always nice. In this case I don't think that we actually need the scripts in their current form as they are just oneliners after all. If the scripts did a bit more (like an intelligent start/stop based on the state of the cluster) it would make sense to have them, but otherwise they act just as an extra layer of abstraction.

2022-05-24 09:07 UTC, joelhoisko commented on Documentation/k3d.md
> +./Environment/k3d/start-local-k3d
```suggestion
k3d cluster start dolittle-dev
```

We actually only need one line in the script, the `k3d` command works globally so we don't have to `cd` anywhere. So I don't think that you even need the separate script files, just documenting the `k3d cluster start/stop dolittle-dev` is enough.

2022-05-24 09:07 UTC, joelhoisko commented on Documentation/k3d.md
> +./Environment/k3d/stop-local-k3d
```suggestion
k3d cluster stop dolittle-dev
```

Same thing here, it's enough to just document the command.

2022-08-16 06:36 UTC, jakhog commented
As this PR has been laying dead here for a while now, I've taken the liberty of applying Joels suggestion - and I will get them in. Thanks Victor!

2022-08-16 06:37 UTC, merged