Bringing back before navigation for now
dolittle/Studio pull request #37
Opened 2020-12-16 18:48 UTC by einari

2020-12-17 13:13 UTC, jakhog requested changes
Some minor suggestions, but one question:

How do we use this from within the iframe? I see how it's used with the `NavigationItem`s that is sent back to the portal, but is there a component to use for links within the frames? Or do we use the `INavigator` in `onclick` events for moving around?

2020-12-17 17:59 UTC, einari commented
> Some minor suggestions, but one question:
> 
> How do we use this from within the iframe? I see how it's used with the `NavigationItem`s that is sent back to the portal, but is there a component to use for links within the frames? Or do we use the `INavigator` in `onclick` events for moving around?

That would've been helpful of me to include info on :) 
I didn't think too much about it being called directly from within a Microservice for the navigation - but that can be added as well. But in general the idea was that the Navigation system found in @shared/portal/navigation/Navigation - it has NavigationItems and on them you can now say which route/path to use for items that will be in the left most menu.

2020-12-17 18:00 UTC, einari commented on Source/Portal/Web/layouts/TopLevelMenuViewModel.ts
>      }
Thanks.. Good catch - leftovers indeed.

2020-12-17 18:04 UTC, einari commented on Source/Shared/Web/routing/RoutingViewModel.tsx
> +            const actualPath = `/_${_.path}`;
I see a pattern emerging :)

2020-12-17 18:08 UTC, einari commented on Source/Shared/WebPack/frontend/devServer.js
> +            });
WebPack DevServer does not seem to function properly with HistoryAPIFallback for DevServers that has a basePath. It didn't fallback to index.html for all routes as it should. So I implemented a fallback that serves the finished rendered index.html. To be able to do that I had to create a plugin that uses the WebPack hooks and gets called when the index.ejs has been "rendered" to index.html and keep it in memory. Also known as "trickster in Ludo"

2020-12-17 18:50 UTC, jakhog commented on Source/Shared/WebPack/frontend/devServer.js
> +            });
Aha, yes that's a real Ludo trick you got there 😛

2020-12-17 18:55 UTC, jakhog reviewed
That makes sense, and for now I don't think we need any special thing for navigating from inside the frames. So should we leave that as an exercise for later?

2020-12-17 18:55 UTC, jakhog commented on Source/Shared/Web/routing/MicroserviceRoute.tsx
> +                innerProps.path = innerProps.path.replace('//', '/');
Now we shouldn't need this right?
```suggestion
```

2020-12-17 18:55 UTC, jakhog commented on Source/Shared/Web/routing/RoutingViewModel.tsx
> +            const actualPath = `/_${path}`;
And we need a `/` here:
```suggestion
            const actualPath = `/_/${path}`;
```

2020-12-18 15:22 UTC, einari commented
Merged and we now have navigation from menu with deep linking :) 

![2020-12-18_16-19-02 (1)](https://user-images.githubusercontent.com/134365/102630752-386eba00-414d-11eb-8236-c4404995fd19.gif)

2020-12-25 05:56 UTC, merged